version: '3'
services:
  db:
    container_name: db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
  server:
    container_name: server
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db
volumes:
  data: